INSERT INTO questions (quiz_id, text)
VALUES (1, 'What sport has the most fans in the world?'),
(1, 'What sport was not in the 2020 olympics?'),
(1, 'What nba player has the most rings?'),
(1, 'Which of the following countries has not hoseted the olympics?'),
(1, 'Eulid Kipchoge is the only person to run a sub 2h marathon. Which country does he race for?'),
(1, 'What is the championship trophy for the CFL called?'),
(2, 'Which of the following pairs of operations are in correct order?'),
(2, 'Whats the answer of 4 x 6 + 8 ÷ 4 ?'),
(2, 'Which of the following equations has a larger outcome? 7 x 3 + 2 or 7 x ( 3 + 2)'),
(2, 'What is the answer of (8/(2²)) x 1/2'),
(3, 'Stop! I couldda dropped my ...'),
(3, 'Road work ahead?...'),
(3, 'Sleep? I dont know about sleep ...' ),
(3, 'When will you learn...' ),
(4, 'What is the captial of Canada?'),
(4, 'What is the captial of Colombia?'),
(4, 'What is the captial of the country with the largest population?'),
(4, 'What is the captial of the country with the largest area?'),
(4, 'What is the captial of the first country to elect a female president?'),
(5, 'Which of the following are not shades of red?'),
(5, 'Which country does not have Spanish as an official language?'),
(5, 'Which of these birds can fly?'),
(5, 'Which countries capital does not have the same name as its country?');
