INSERT INTO answers (question_id, text, correct)
VALUES (1, 'Soccer', true),
(1, 'Basketball', false),
(1, 'Baseball', false),
(1, 'Hockey', false),
(2, 'wrestling', true),
(2, 'Golf', false),
(2, 'Rugby', false),
(2, 'Surfing', false),
(3, 'Bill Russel', true),
(3, 'Micheal Jordan', false),
(3, 'LeBron James', false),
(3, 'Scottie Pippen', false),
(4, 'Egypt', true),
(4, 'Mexico', false),
(4, 'Italy', false),
(4, 'Sweden', false),
(5, 'Kenya', true),
(5, 'USA', false),
(5, 'Ethiopia', false),
(5, 'Eritrea', false),
(6, 'Grey Cup', true),
(6, 'Stanley Cup', false),
(6, 'Piston Cup', false),
(6, 'Vince Lombardi Trophy', false),
(7, 'Multiplication then subtraction', true),
(7, 'Multiplication then brackets', false),
(7, 'Subtraction then division', false),
(7, 'Multiplication then exponents', false),
(8, '26', true),
(8, '32', false),
(8, '12', false),
(8, '84', false),
(9, '7 x ( 3 + 2 )', true),
(9, '7 x 3 + 2', false),
(9, 'They are equal', false),
(9, 'I dont know', false),
(10, '1', true),
(10, '2', false),
(10, '4', false),
(10, '8', false),
(11, 'croissant!', true),
(11, 'juice', false),
(11, 'my plate', false),
(11, 'beet', false),
(11, 'croissant.', true),
(11, 'juice.', false),
(11, 'my plate.', false),
(11, 'beet.', false),
(12, 'Uh yeah, I sure hope it does.', true),
(12, 'It better be!', false),
(12, 'Not on my watch.', false),
(12, 'why wouldnt it ...', false),
(13, 'its summertime.', true),
(13, 'I have insomnia', false),
(13, 'how long have I been sitting here', false),
(13, 'not on my watch', false),
(14, 'that your actions have consequences', true),
(14, 'how to be a real boy pinocchio', false),
(14, 'the true meaning of Christmas', false),
(14, 'your fantasies cant ever be quenched', false),
(15, 'Ottawa', true),
(15, 'Toronto', false),
(15, 'Montreal', false),
(15, 'Vancouver', false),
(16, 'Bogotá', true),
(16, 'Lima', false),
(16, 'Santo Domingo', false),
(16, 'San Juan', false),
(17, 'Beijing', true),
(17, 'New Delhi', false),
(17, 'Shanghai', false),
(17, 'Tokyo', false),
(18, 'Moscow', true),
(18, 'Kyiv', false),
(18, 'Saint Petersburg', false),
(18, 'Warsaw', false),
(19, 'Reykjavík', true),
(19, 'Berlin', false),
(19, 'Munich', false),
(19, 'Stockholm', false),
(20, 'chartreuse', true),
(20, 'crimson', false),
(20, 'scarlet', false),
(20, 'vermilion', false),
(21, 'Brazil', true),
(21, 'Bolivia', false),
(21, 'Costa Rica', false),
(21, 'Equatorial Guinea', false),
(22, 'turkey', true),
(22, 'kiwi', false),
(22, 'emu', false),
(22, 'penguin', false),
(23, 'El Salvador', true),
(23, 'Luxembourg', false),
(23, 'Vatican City', false),
(23, 'Guatemala', false);

