INSERT INTO answers (question_id, text, correct) VALUES (1, 'soccer', true),
(1, 'Basketball', false),
(1, 'Baseball', false),
(1, 'Hockey', false),
(2, '26', true),
(2, '32', false),
(2, '12', false),
(2, '84', false),
(3, 'bh/2', true),
(3, 'bh', false),
(3, 'bh/4', false),
(3, '3bh/2', false),
(4, 'Ottawa', true),
(4, 'Toronto', false),
(4, 'Montreal', false),
(4, 'Vancouver', false),
(5, 'Dwayne Johnson', true),
(5, 'Anthony Hopkins', false),
(5, 'Riz Ahmed', false),
(5, 'Steven Yeun', false);
